### ISSUE TITLE
Elasticsearch.pm is not available anymore.

### ISSUE THREAD

**Issue by jakommo** [chetanganatra/Excel-2-Elasticsearch#2]
As Elasticsearch.pm isn't on cpan anymore it's hard to get this running.
Had to install manually from backpan.perl.org.
The official client is now Search::Elasticsearch, would it be possible to switch to this module?

**Comment by chetanganatra** [comment]
Sure. Once time permits, let me check and port it to use Search::Elasticsearch.
Thanks for pointing out..have not being using it for a quite some time now.

**Comment by driv** [comment]
I've tried to change Elasticsearch to Search::Elasticsearch inside the script, but I'm getting:

```bash
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.
substr outside of string at ./xl2es.pl line 116.

XL2ES :> 09/01/2015 21:02 Total records inserted: 1126 
```

The data is inserted but everything is:
```json
         {
            "type" : "string",
            "index" : "not_analyzed"
         },
```

**Comment by jakommo** [comment]
@driv I ended up installing the old module from backpan.perl.org as it's not as easy as just changing the module name.

**Comment by chetanganatra** [comment]
Made the changes required for the official Search::Elasticsearch module. Tested and found it working. If you still face the issue with mapping, try using the verbose (-v) option and share the output.

**Comment by chetanganatra** [comment]
Closing after test confirmed
