### ISSUE TITLE
Integer is not working.

### ISSUE THREAD

**Issue by rodrigograca31** [chetanganatra/Excel-2-Elasticsearch#3]
After Importing some data I noticed that the Integer fields are not created as they should, so I imported the example .xls file:
![example](http://i.imgur.com/aYq25WK.png)

**Comment by chetanganatra** [comment]
Not sure what exactly is the problem that you are facing. If it's still not solved yet, share a sample column and data so I can try out.

Field name format could be like age_NI where age is field name, N implies Not_Analyzed index and I implies Integer. You can use B for Double and S for string as the last character.

**Comment by rodrigograca31** [comment]
The Age and Serial fields should not have double quotes arround them... That means they are a string and not an Integer....

**Comment by chetanganatra** [comment]
Try the sample xls and revert if you still unable to get it working.
