### ISSUE TITLE
Not able to run the command.

### ISSUE THREAD

**Issue by ghost** [chetanganatra/Excel-2-Elasticsearch#5]
Installed strawberry pearl, the pre-requisites and still not able to get the command working.

Please find the attached screenshot. Even though the search::es is installed, it's not showing.

Kindly help. :)

![elastic pl error](https://cloud.githubusercontent.com/assets/16775942/12807642/a3d38678-cb36-11e5-81dc-5054a247c133.png)

**Comment by chetanganatra** [comment]
Hi Anoop, the error snapshot suggests that perl is not able to locate the elasticsearch module itself.

You need to fix it first to get the code working. xl2es was developed in ActiveState perl, you may want to try the same.
